# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "creating chefs"
Chef.create(name:"Meowscular Chef" , image_url: "https://thumbs.gfycat.com/WhisperedWelllitDassierat-poster.jpg",video_url:"https://youtu.be/fsJx94RSc_Q" , location:"Astera")
Chef.create(name:"Grammeowster Chef" , image_url: "https://pm1.narvii.com/7323/2c4ce61929ab8093f0c7497e2835e081bfff041cr1-1334-750v2_hq.jpg",video_url: "https://youtu.be/AFIXAvOQBMc", location:"Seliana")

puts "creating meals"
Meal.create(name:"Fat Cat", image_url:"https://cdn.gamer-network.net/2018/usgamer/monster-hunter-world-canteen-eating.png", video_url: "https://www.youtube.com/watch?v=UbRcBEB2dmM",chef_id: Chef.first.id)
Meal.create(name:"Cool Cat", image_url:"https://i.ytimg.com/vi/0sALjbK_5jM/maxresdefault.jpg", video_url: "https://www.youtube.com/watch?v=KZ27YBtwaP0",chef_id: Chef.first.id)
Meal.create(name:"Felyne Fisher", image_url:"https://assets.rockpapershotgun.com/images/2018/08/20180726122812_1.jpg", video_url: "https://www.youtube.com/watch?v=8nNHBePVAxc", chef_id: Chef.first.id)
Meal.create(name:"Lucky Cat", image_url:"https://static.wikia.nocookie.net/d44a9097-c6c4-4430-bb69-3168c92d0c18", video_url:"https://youtu.be/AFIXAvOQBMc" ,chef_id: Chef.second.id)

puts "creating dish"
Dish.create(name: "TURKEY", image_url: "https://images-gmi-pmc.edge-generalmills.com/efc328a5-f18d-45f6-9b09-dd44023c3ee8.jpg", meal_id: Meal.find_by(name:"Fat Cat").id )
Dish.create(name: "FISH STEW", image_url: "https://i.pinimg.com/originals/f3/ea/b3/f3eab333f06fdf5bb7e11ee1dc3145be.jpg", meal_id: Meal.find_by(name:"Fat Cat").id )
Dish.create(name: "SHRIMP SKEWERS", image_url: "https://natashaskitchen.com/wp-content/uploads/2015/05/Grilled-Garlic-Cajun-Shrimp-Skewers-4-500x500.jpg" , meal_id: Meal.find_by(name:"Fat Cat").id )
Dish.create(name: "CHICKEN SKEWERS", image_url:"https://toriavey.com/images/2014/07/MG_3442.jpg", meal_id: Meal.find_by(name:"Fat Cat").id )
Dish.create(name: "SAUSAGE SKEWERS", image_url: "https://recipes.grillgrate.com/wp-content/uploads/2017/06/golden_toad.jpg", meal_id: Meal.find_by(name:"Fat Cat").id )



Dish.create(name: "Paella", image_url: "https://c.ndtvimg.com/2019-09/7euvij3_paella_625x300_23_September_19.jpg", meal_id: Meal.find_by(name:"Cool Cat").id )
Dish.create(name: "Roast Beef", image_url: "https://cookthestory.com/wp-content/uploads/2018/11/Roast-Beef-1392x780-2123.jpg", meal_id: Meal.find_by(name:"Cool Cat").id )
Dish.create(name: "Lobster Bisque", image_url: "https://www.tasteofhome.com/wp-content/uploads/2020/03/Lobster-Bisque_EXPS_FT20_250649_F_0206_1.jpg", meal_id: Meal.find_by(name:"Cool Cat").id )
Dish.create(name: "Shrimp Skewers", image_url: "https://natashaskitchen.com/wp-content/uploads/2015/05/Grilled-Garlic-Cajun-Shrimp-Skewers-4-500x500.jpg", meal_id: Meal.find_by(name:"Cool Cat").id )
Dish.create(name: "Beef Skewers", image_url: "https://cook.fnr.sndimg.com/content/dam/images/cook/fullset/2012/8/11/0/CCGMK_Mr-Xues-Muslim-Beef-Skewers-recipe_s4x3.jpg.rend.hgtvcom.826.620.suffix/1351634095334.jpeg", meal_id: Meal.find_by(name:"Cool Cat").id )
Dish.create(name: "Chicken Skewers", image_url: "https://toriavey.com/images/2014/07/MG_3442.jpg", meal_id: Meal.find_by(name:"Cool Cat").id )


Dish.create(name: "Fish", image_url: "https://erecipe.com/wp-content/uploads/2017/02/78abf035af7adb92ad58d3c8c4d928d3ef1ab70c.jpg", meal_id: Meal.find_by(name:"Felyne Fisher").id)
Dish.create(name: "Rolls", image_url: "https://www.thespruceeats.com/thmb/5kZ3ECSvTR4A0zLNAMF-0l-E4kc=/450x0/filters:no_upscale():max_bytes(150000):strip_icc()/buns-in-oven-471345753-5c0204a5c9e77c00012e5ef6.jpg", meal_id: Meal.find_by(name:"Felyne Fisher").id)
Dish.create(name: "Vegetable Soup", image_url: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/7/19/0/WU1908_Roasted-Vegetable-Soup_s4x3.jpg.rend.hgtvcom.826.620.suffix/1532028539615.jpeg", meal_id: Meal.find_by(name:"Felyne Fisher").id)
Dish.create(name: "Sausage Skewers", image_url: "https://recipes.grillgrate.com/wp-content/uploads/2017/06/golden_toad.jpg", meal_id: Meal.find_by(name:"Felyne Fisher").id)
# Dish.create(name: , image_url: , meal_id: Meal.find_by(name:"Felyne Fisher").id)

Dish.create(name:"MAC AND CHEESE" , image_url: "https://feastandfarm.com/wp-content/uploads/macandcheese-500x375.jpg", meal_id:Meal.find_by(name:"Lucky Cat").id )
Dish.create(name:"GARLICKY SAUSAGE" , image_url: "https://cuetopiatexas.com/wp-content/uploads/2015/12/garlic-texas-sausage-1.jpg", meal_id:Meal.find_by(name:"Lucky Cat").id )
Dish.create(name:"SPICY SAUSAGE" , image_url: "https://honest-food.net/wp-content/uploads/2017/07/spicy-Italian-sausage-recipe.jpg", meal_id:Meal.find_by(name:"Lucky Cat").id )
Dish.create(name:"BAGUETTE" , image_url: "https://www.kingarthurflour.com/sites/default/files/styles/featured_image/public/recipe_legacy/8-3-large.jpg?itok=fRNQugY8", meal_id:Meal.find_by(name:"Lucky Cat").id )
Dish.create(name:"MUSHROOM SOUP" , image_url: "https://www.budgetbytes.com/wp-content/uploads/2017/09/Creamy-Garlic-Mushroom-Soup-spoon.jpg", meal_id:Meal.find_by(name:"Lucky Cat").id )
Dish.create(name:"BEEF STEW" , image_url: "https://embed.widencdn.net/img/mccormick/btxmwcorsu/1365x1365px/Easy%20Beef%20Stew_2019-04-10_9153_TSUCALAS.jpg?crop=true&anchor=397,0&q=80&color=ffffffff&u=o2hyef", meal_id:Meal.find_by(name:"Lucky Cat").id )



puts "creating recipes"

Recipe.create(dish_id: Dish.find_by(name:"MAC AND CHEESE").id , ingredients:"1600 g milk, 0.5 tsp nutmeg, 1 tsp Black pepper, 1 tsp salt, 500 g ziti macaroni, 90 g butter, 60 g flour, 374 g mascarpone cheese, 250 g Gruyère des grottes", instructions:"Cook the pasta for four minutes less than called for on the package. Drain the pasta, add to the boiled milk and cook for two minutes. Melt butter in the pan, add flour and mix, add milk and stir until thickened. Cut 200g of Gruyère cheese into cubes, grate 50g into shreds. Mix all the ingredients and sprinkle shredded cheese on top. Bake at 180C for 30minutes.")
Recipe.create(dish_id: Dish.find_by(name:"GARLICKY SAUSAGE").id, ingredients: "1000 g pork shoulder, 1 tsp Mustard seeds, 17 g Salt, 1 tbsp Brown sugar, 1 tbsp Black pepper, 1 ear garlic, 2 tsp fresh thyme, Casing", instructions:"Mince the pork shoulder. Mix all the ingredients.Soak casing in water for 10 minutes.Run water through the casing to check if there are any holes.Stuff the meat into casing.Poke the casing with a fork to prevent from bursting.Pinch off and spin the link.Keep in the refrigerator for one night.Cut the link and cook in 80C degree hot water until sausages float.Pan-fry the sausage until golden brown.")
Recipe.create(dish_id: Dish.find_by(name:"SPICY SAUSAGE").id, ingredients: "1000 g pork shoulder, 17 g salt,  2 g Garlic, 2 tbsp Fennel seed, 1 tsp Black pepper, 1 tbsp Sugar, 2 tbsp Red pepper flakes, Casing", instructions:"Mince the pork shoulder. Mix all the ingredients.Soak casing in water for 10 minutes.Run water through the casing to check if there are any holes.Stuff the meat into casing.Poke the casing with a fork to prevent from bursting.Pinch off and spin the link.Keep in the refrigerator for one night.Cut the link and cook in 80C degree hot water until sausages float.Pan-fry the sausage until golden brown.")
Recipe.create(dish_id: Dish.find_by(name:"BAGUETTE").id, ingredients:"Dough starter, 113 g Cool water, 1/16 tsp Instant yeast, 120 g All-purpose flour, 255 g Lukewarm water, 418 g All-purpose flour, Bread Dough, All the starter, 1.5 tsp Instant yeast, 2 tsp Salt" , instructions:"Mix dough starter and cover with a lid. Ferment at room temperature for 14 hours or overnight. Mix all the ingredients together in a stand mixer for 10 minutes at low speed. Let rise in a container with a lid for 90 minutes. Deflate the dough and divide it into 4 portions. Roll each dough into a ball and let rest for 90 minutes. Deflate doughs and fold into a log shape. Let rise in a warm place for one hour. Slash the dough with a sharp knife and bake at 250C for 30 minutes. Let cool and serve.")
Recipe.create(dish_id: Dish.find_by(name:"MUSHROOM SOUP").id, ingredients: "50 g dried mushrooms, 600 g water, 2 ea shallots, 1 ea garlic, 200 g button mushrooms, 100 g boletus, 2 tbsp butter, 400 g vegetable stock, 3 ea egg yolks, 200 g heavy cream, 1/2 tsp nutmeg (grated), salt, pepper", instructions:"Soak dried mushrooms in warm water for 15 minutes. Cut button mushrooms, shallots and garlic into shreds. Stir fry button mushrooms, shallots and garlic with 2/3 butter until soft. Add vegetable stock and mushroom water. Grate nutmeg into the soup. Cook for 20 minutes. Blend until smooth. Mix egg yolks and heavy cream, then add into the soup. Bring to a boil and add salt and pepper to taste. Stir fry sliced boletus with butter. Put on top of the soup.")
Recipe.create(dish_id: Dish.find_by(name:"BEEF STEW").id, ingredients: "1000 g Beef, Beef stock, Black pepper, Salt, 500 g Baby potatoes, 2 ea Carrots, 1 ea Onion, 3 clove Garlic, 1 ea Broccoli, 2 tbsp Tomato paste, 1 tbsp  Worcestershire sauce, 1 tsp thyme, 1 tsp Rosemary, 1 tsp Paprika, 1 tsp Caraway seeds, 2 ea Bay leaves", instructions:"Sprinkle salt and pepper on beef and seal in a frypan. Then add all the ingredients into a slow cooker and cook for 4 hours.")

Recipe.create(dish_id: Dish.find_by(name:"Paella").id, ingredients: "4 small lobster tails (6-12 oz each), Water, 3 tbsp Private Reserve Extra Virgin Olive Oil, 1 large yellow onion, chopped, 2 cups Spanish rice or medium-grain rice, soaked in water for 15 to 20 minutes and then drained, 4 garlic cloves, chopped, 2 large pinches of Spanish saffron threads soaked in 1/2 cup water, 1 tsp Sweet Spanish paprika, 1 tsp cayenne pepper, 1/2 tsp aleppo pepper flakes, Salt, 2 large Roma tomatoes, finely chopped, 6 oz French green beans, trimmed, 1 lb prawns or large shrimp or your choice, peeled and deveined, 1/4 cup chopped fresh parsley", instructions: "In a large pot, bring 3 cups of water to a rolling boil. Add the lobster tails and let boil very briefly (1-2 minutes) until pink. Turn the heat off. Remove the lobster tails with a pair of tongs. Do not discard the lobster cooking water. When the lobster is cool enough to handle, remove the shell and cut into large chunks. In a large deep pan or cast iron skillet, heat 3 tbsp olive oil. Turn the heat to medium-high and add the chopped onions. Saute the onions for 2 minutes then add the rice, and cook for 3 more minutes, stirring regularly. Now add the chopped garlic and the lobster cooking water. Stir in the saffron and it’s soaking liquid, paprika, cayenne pepper, aleppo pepper, and salt. Stir in the chopped tomatoes and green beans. Bring to a boil and let the liquid slightly reduce, then cover (with lid or tightly with foil) and cook on low heat for 20 minutes. Uncover and spread the shrimp over the rice, pushing it into the rice slightly. Add a little water if needed. Cover and cook for another 10 minutes or until the shrimp turns pink. Finally, add the cooked lobster chunks. When the lobster is warmed through, turn heat off. Garnish with parsley. Serve the paella hot with your favorite white wine.")
Recipe.create(dish_id: Dish.find_by(name:"Roast Beef").id, ingredients: "3 pounds beef eye of round roast, ½ teaspoon kosher salt, ½ teaspoon garlic powder, ¼ teaspoon freshly ground black pepper", instructions: "Preheat oven to 375 degrees F (190 degrees C). If roast is untied, tie at 3 inch intervals with cotton twine. Place roast in pan, and season with salt, garlic powder, and pepper. Add more or less seasonings to taste. Roast in oven for 60 minutes (20 minutes per pound). Remove from oven, cover loosely with foil, and let rest for 15 to 20 minutes.")
Recipe.create(dish_id: Dish.find_by(name:"Lobster Bisque").id, ingredients: "4 tbsp. Butter, 1 medium onion, finely chopped, 2 carrots, peeled and finely chopped, 2 stalks celery, finely chopped, Kosher salt, Freshly ground black pepper, 2 cloves garlic, minced, 2 tbsp. tomato paste, 2 tbsp. all-purpose flour, 4 c. seafood or fish stock, 1 1/4 c. dry white wine, 1 bay leaf, 3 sprigs fresh thyme, 1/2 c. heavy cream, 1 lb. cooked lobster meat, chopped, Finely chopped chives, for serving", instructions: "In a large, heavy pot over medium heat, heat butter. Add onion, carrots, and celery and cook until soft, about 7 minutes. Season with salt and pepper, then stir in garlic and tomato paste. Cook until garlic is fragrant and tomato paste coats vegetables, about 2 minutes. Sprinkle over flour and cook, 1 minute more. Pour in seafood stock and wine, then stir in bay leaf and thyme. Reduce heat and let simmer until liquid is reduced and flavors meld, stirring occasionally, 30 minutes. Remove bay leaf and thyme and purée with an immersion blender until very smooth. Return to medium-low heat and stir in heavy cream and lobster meat, cooking just until warm, about 5 minutes. Garnish with chives before serving.")
Recipe.create(dish_id: Dish.find_by(name:"Shrimp Skewers").id, ingredients: "20 shrimp cleaned and tails left on, 1 tbsp garlic paste, 1/4 cup olive oil, 1 tsp red wine vinegar, juice of 1 lemon, 1 tbsp oregano, 1 tsp paprika, 1 tsp salt, 1 tsp pepper, 1 tsp sugar, 5 wooden skewers", instructions: "Place all the ingredients in a ziplock bag and toss to coat the shrimp. Seal and refrigerate for at least 1 hour to a maximum of 3 hours. Take your wooden skewers and let them sit in water for 30 minutes. This will prevent them from burning on the grill. Pierce the shrimp with a wooden skewer. Place 4 pieces of shrimp on each skewer. Preheat your grill. Once the grill is nice and hot, oil the grate to prevent the skewers from sticking. Cook directly over the heat and cook for about 2 minutes per side or until the shrimp is no longer transparent.")
Recipe.create(dish_id: Dish.find_by(name:"Beef Skewers").id, ingredients: "1 1/2 lb boneless beef ribs cut into large cubes, 2 tbsp garlic paste, 1/4 cup olive oil, 1 tbsp steak sauce, 3 tbsp red wine vinegar, juice of 1 lemon, 2 tbsp oregano, 1 tsp cardamom, 1 tsp salt, 2 tsp pepper, 2 tsp brown sugar, 6-8 wooden skewers", instructions: "Place all the ingredients in a bowl and toss to coat the beef. Cover and refrigerate for at least 1 hour to a maximum of 3 hours. Take your wooden skewers and let them sit in water for 30 minutes. This will prevent them from burning on the grill. Pierce the beef with a wooden skewer. Place 4-6 pieces of beef on each skewer. Preheat your grill. Once the grill is nice and hot, oil the grate to prevent the skewers from sticking. Cook directly over the heat and turn the skewers every 3-4 minutes until each side of the skewer has a nice char.")
Recipe.create(dish_id: Dish.find_by(name:"Chicken Skewers").id, ingredients: "2 lbs chicken breast cut into large cubes, 3 tbsp garlic paste, 1 cup greek yogurt, 1/4 cup olive oil, 3 tbsp red wine vinegar, juice of 1 lemon, 2 tbsp oregano, 1 tsp pepper, 1 tbsp salt, 1 tsp paprika, 6-8 wooden skewers", instructions: "Place all the ingredients in a bowl and toss to coat the chicken. Cover and refrigerate for at least 3 hour to a maximum of 6 hours. Take your wooden skewers and let them sit in water for 30 minutes. This will prevent them from burning on the grill. Pierce the chicken with a wooden skewer. Place 4-6 pieces of chicken on each skewer. Preheat your grill. Once the grill is nice and hot, oil the grate to prevent the skewers from sticking. Cook directly over the heat and turn the skewers every 3-4 minutes until each side of the skewer has a nice char.")

Recipe.create(dish_id: Dish.find_by(name:"TURKEY").id, ingredients:"12 pound (6 kg) whole turkey, skin on (fully defrosted, washed, giblets and neck removed),3 heads garlic cut in half horizontally divided, 3 slices lemon divided, 6 sprigs thyme divided, 6 sprigs rosemary divided, 1/2 cup olive oil divided, Herb Butter" , instructions: "Preheat oven to 425°F | 220°C for standard ovens, or 390°F | 200°C for fan forced. Lower oven shelf to the lowest part of your oven. Combine the Herb Butter ingredients in a bowl and mix well. Reserve half of the herb butter in the refrigerator for later. Line a large roasting pan with foil or parchment paper. Arrange the 4 halves of garlic cut-side down on the bottom of the pan with 4 sprigs each of thyme and rosemary, half of the olive oil and 1 slice of lemon. Thoroughly pat turkey dry with paper towels. Stuff with the remaining heads garlic halves, lemon slice, a squeeze of lemon from remaining slice, herbs and a drizzle of olive oil. Melt the butter and rub all over the turkey, including under the skin. Season generously all over with salt and pepper. Place turkey on top of the garlic and herbs in the pan BREAST-SIDE DOWN. Drizzle with the remaining oil. Roast uncovered for 30 minutes for a small turkey under 13 pounds (6 1/2 kg), or 45 minutes for a larger turkey over 14 pounds (7 kg plus). Turn turkey over (breast-side up) with a clean tea towel or oven mits (heat-proof gloves) and baste with pan juices. Using the reserved herb butter, use a spoon to spread half of it over the top of your turkey (be careful, the turkey will be hot and the butter will melt nicely over the skin). Pour any remaining juices over your turkey. Reduce heat to 325°F |165°C (for standard ovens), or 300°F | 150°C (fan-forced). Roast for an hour. Slather turkey generously with remaining butter and roast for 30 minutes. Baste again, then continue roasting for a further 30 minutes or so, depending on the size of your bird.(For an extra large turkey, you may need an additional half hour to an hour. Tent loosely with foil if starting to brown too fast.) For extra crispy skin, broil (or grill) in the last 5-10 minutes, keeping your eye on it so it doesn't burn, until the skin is crispy and golden browned all over. Tent turkey with foil and allow it to rest for 20-30 minutes before carving and serving. Remove 2 1/2 cups of the liquid from the pan juices (top up with stock if you need too), strain and reserve for your gravy.")
Recipe.create(dish_id: Dish.find_by(name:"FISH STEW").id , ingredients: "6 tablespoons extra virgin olive oil, 1 medium onion, chopped (about 1 1/2 cups), 3 large garlic cloves minced, 2/3 cup fresh parsley chopped, 1 1/2 cups of fresh chopped tomato (about 1 medium sized tomato) OR 1 14-ounce can of whole or crushed tomatoes with their juices, 2 teaspoons tomato paste (optional), 8 oz of clam juice (or shellfish stock), 1/2 cup dry white wine (like Sauvignon blanc), 1 1/2 lb fish fillets (use a firm white fish such as halibut, cod, red snapper, or sea bass), cut into 2-inch pieces Pinch of dry oregano, Pinch of dry thyme, 1/8 teaspoon Tabasco sauce (or more to taste), Freshly ground black pepper to taste, Salt to taste", instructions: "Heat olive oil in a large thick-bottomed pot over medium-high heat. Add onion and sauté 4 minutes, add the garlic and cook a minute more. Add parsley and stir 2 minutes. Add tomato and tomato paste, and gently cook for 10 minutes or so.  Add clam juice, dry white wine, and fish. Bring to a simmer and simmer until the fish is cooked through and easily flakes apart, about 3 to 5 minutes. Add seasoning (oregano, thyme, Tabasco). Add salt and pepper to taste. Ladle into bowls and serve. Great served with crusty bread for dipping in the fish stew broth.")
Recipe.create(dish_id: Dish.find_by(name:"SHRIMP SKEWERS").id , ingredients: "20 shrimp cleaned and tails left on, 1 tbsp garlic paste, 1/4 cup olive oil, 1 tsp red wine vinegar, juice of 1 lemon, 1 tbsp oregano, 1 tsp paprika, 1 tsp salt, 1 tsp pepper, 1 tsp sugar, 5 wooden skewers", instructions: "Place all the ingredients in a ziplock bag and toss to coat the shrimp. Seal and refrigerate for at least 1 hour to a maximum of 3 hours. Take your wooden skewers and let them sit in water for 30 minutes. This will prevent them from burning on the grill. Pierce the shrimp with a wooden skewer. Place 4 pieces of shrimp on each skewer. Preheat your grill. Once the grill is nice and hot, oil the grate to prevent the skewers from sticking. Cook directly over the heat and cook for about 2 minutes per side or until the shrimp is no longer transparent.")
Recipe.create(dish_id: Dish.find_by(name:"CHICKEN SKEWERS").id , ingredients: "2 lbs chicken breast cut into large cubes, 3 tbsp garlic paste, 1 cup greek yogurt, 1/4 cup olive oil, 3 tbsp red wine vinegar, juice of 1 lemon, 2 tbsp oregano, 1 tsp pepper, 1 tbsp salt, 1 tsp paprika, 6-8 wooden skewers", instructions: "Place all the ingredients in a bowl and toss to coat the chicken. Cover and refrigerate for at least 3 hour to a maximum of 6 hours. Take your wooden skewers and let them sit in water for 30 minutes. This will prevent them from burning on the grill. Pierce the chicken with a wooden skewer. Place 4-6 pieces of chicken on each skewer. Preheat your grill. Once the grill is nice and hot, oil the grate to prevent the skewers from sticking. Cook directly over the heat and turn the skewers every 3-4 minutes until each side of the skewer has a nice char." )
Recipe.create(dish_id: Dish.find_by(name:"SAUSAGE SKEWERS").id , ingredients: "5 Italian sausage links- hot or mild, some onion - cut into squares, red pepper- cut into squares", instructions: "Cut the sausage into 4 equally sized pieces. Starting with the pepper squares, thread the sausage and veg onto a skewer, ending with a red pepper at the end. Brush with olive oil if desired, but not necessary. Grill over a hot bbq or under a hot broiler, turning often, until fully cooked. Serve with rice, a salad, some potatoes or rapini and some fresh, crusty bread.")


Recipe.create(dish_id: Dish.find_by(name:"Fish").id , ingredients: "2 whole sea bass cleaned and scaled, 3 tbsp of olive oil, 1 tbsp of fresh oregano chopped, 2 lemons zested juiced and sliced, 1 tsp of ground coriander, salt to taste, 1/4 tsp of ground black pepper, 2 large oregano sprigs", instructions: "Heat olive oil in a large thick-bottomed pot over medium-high heat. Add onion and sauté 4 minutes, add the garlic and cook a minute more. Add parsley and stir 2 minutes. Add tomato and tomato paste, and gently cook for 10 minutes or so.  Add clam juice, dry white wine, and fish. Bring to a simmer and simmer until the fish is cooked through and easily flakes apart, about 3 to 5 minutes. Add seasoning (oregano, thyme, Tabasco). Add salt and pepper to taste. Ladle into bowls and serve. Great served with crusty bread for dipping in the fish stew broth.")
Recipe.create(dish_id: Dish.find_by(name:"Vegetable Soup").id , ingredients: "2 tbsp extra virgin olive oil, 1 large onion diced, 3 cloves garlic minced, 3 medium carrots diced, 3 stalks celery diced, 2 medium potatoes peeled and diced, 2 tsp Italian seasoning, 4 cups vegetable broth + 1 cup water, 2–15oz can diced tomatoes, 1 cup corn (I used thawed from frozen), 1–15oz can kidney beans drained and rinsed (optional), 1 bay leaf, 1/4 cup parsley, chopped, 1 tbsp freshly squeezed lemon juice more to taste, 1 1/2 tsp kosher salt more to taste, Freshly ground black pepper", instructions: "Heat oil in a large dutch oven over medium-low heat. Once hot, add onion, garlic and a teaspoon of kosher salt and cook about 8 minutes. Add carrots, celery, potatoes and cook for 5 more minutes, stirring often. Add Italian seasoning and cook for one more minute.Add broth, water, tomatoes, corn, beans, bay leaf, and several grinds of pepper. Bring to a boil and then reduce the heat to low and simmer, covered until the vegetables are tender, about 35 minutes. Remove from heat and stir in parsley and lemon juice. Remove bay leaf and season to taste with salt (don’t be shy, I added lots of salt!) and pepper. Serve hot with crusty bread.")
Recipe.create(dish_id: Dish.find_by(name:"Sausage Skewers").id , ingredients: "5 Italian sausage links- hot or mild, some onion - cut into squares, red pepper- cut into squares", instructions: "Cut the sausage into 4 equally sized pieces. Starting with the pepper squares, thread the sausage and veg onto a skewer, ending with a red pepper at the end. Brush with olive oil if desired, but not necessary. Grill over a hot bbq or under a hot broiler, turning often, until fully cooked. Serve with rice, a salad, some potatoes or rapini and some fresh, crusty bread." )

